import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs"
import "./globals.css";
import { cn } from "@/lib/utils";
import {dark} from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }} >
      <html lang="en" suppressHydrationWarning>
        <body className={cn(inter.className, 'min-h-svh flex justify-center items-center dark')}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
